// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// recognizer.cpp
SEXP create_offline_recognizer_(std::string model_dir, std::string model_type, std::string encoder_path, std::string decoder_path, std::string joiner_path, std::string model_path, std::string tokens_path, int num_threads, std::string provider, std::string language, std::string modeling_unit);
extern "C" SEXP _sherpa_onnx_create_offline_recognizer_(SEXP model_dir, SEXP model_type, SEXP encoder_path, SEXP decoder_path, SEXP joiner_path, SEXP model_path, SEXP tokens_path, SEXP num_threads, SEXP provider, SEXP language, SEXP modeling_unit) {
  BEGIN_CPP11
    return cpp11::as_sexp(create_offline_recognizer_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_dir), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_type), cpp11::as_cpp<cpp11::decay_t<std::string>>(encoder_path), cpp11::as_cpp<cpp11::decay_t<std::string>>(decoder_path), cpp11::as_cpp<cpp11::decay_t<std::string>>(joiner_path), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_path), cpp11::as_cpp<cpp11::decay_t<std::string>>(tokens_path), cpp11::as_cpp<cpp11::decay_t<int>>(num_threads), cpp11::as_cpp<cpp11::decay_t<std::string>>(provider), cpp11::as_cpp<cpp11::decay_t<std::string>>(language), cpp11::as_cpp<cpp11::decay_t<std::string>>(modeling_unit)));
  END_CPP11
}
// recognizer.cpp
list transcribe_wav_(SEXP recognizer_xptr, std::string wav_path);
extern "C" SEXP _sherpa_onnx_transcribe_wav_(SEXP recognizer_xptr, SEXP wav_path) {
  BEGIN_CPP11
    return cpp11::as_sexp(transcribe_wav_(cpp11::as_cpp<cpp11::decay_t<SEXP>>(recognizer_xptr), cpp11::as_cpp<cpp11::decay_t<std::string>>(wav_path)));
  END_CPP11
}
// recognizer.cpp
void destroy_recognizer_(SEXP recognizer_xptr);
extern "C" SEXP _sherpa_onnx_destroy_recognizer_(SEXP recognizer_xptr) {
  BEGIN_CPP11
    destroy_recognizer_(cpp11::as_cpp<cpp11::decay_t<SEXP>>(recognizer_xptr));
    return R_NilValue;
  END_CPP11
}
// recognizer.cpp
list read_wav_(std::string wav_path);
extern "C" SEXP _sherpa_onnx_read_wav_(SEXP wav_path) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_wav_(cpp11::as_cpp<cpp11::decay_t<std::string>>(wav_path)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_sherpa_onnx_create_offline_recognizer_", (DL_FUNC) &_sherpa_onnx_create_offline_recognizer_, 11},
    {"_sherpa_onnx_destroy_recognizer_",        (DL_FUNC) &_sherpa_onnx_destroy_recognizer_,         1},
    {"_sherpa_onnx_read_wav_",                  (DL_FUNC) &_sherpa_onnx_read_wav_,                   1},
    {"_sherpa_onnx_transcribe_wav_",            (DL_FUNC) &_sherpa_onnx_transcribe_wav_,             2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_sherpa_onnx(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, FALSE);
}
