# Generated by cpp11: do not edit by hand

create_offline_recognizer_ <- function(model_dir, model_type, encoder_path, decoder_path, joiner_path, model_path, tokens_path, num_threads, provider, language, modeling_unit) {
  .Call(`_sherpa_onnx_create_offline_recognizer_`, model_dir, model_type, encoder_path, decoder_path, joiner_path, model_path, tokens_path, num_threads, provider, language, modeling_unit)
}

transcribe_wav_ <- function(recognizer_xptr, wav_path) {
  .Call(`_sherpa_onnx_transcribe_wav_`, recognizer_xptr, wav_path)
}

transcribe_samples_ <- function(recognizer_xptr, samples, sample_rate) {
  .Call(`_sherpa_onnx_transcribe_samples_`, recognizer_xptr, samples, sample_rate)
}

destroy_recognizer_ <- function(recognizer_xptr) {
  invisible(.Call(`_sherpa_onnx_destroy_recognizer_`, recognizer_xptr))
}

read_wav_ <- function(wav_path) {
  .Call(`_sherpa_onnx_read_wav_`, wav_path)
}

extract_vad_segments_ <- function(vad_model_path, samples, sample_rate, vad_threshold, vad_min_silence, vad_min_speech, vad_max_speech, vad_window_size, verbose) {
  .Call(`_sherpa_onnx_extract_vad_segments_`, vad_model_path, samples, sample_rate, vad_threshold, vad_min_silence, vad_min_speech, vad_max_speech, vad_window_size, verbose)
}
